config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
                       sessions: 'auth/users/sessions' ,
                       registrations: 'auth/users/registrations',
                       passwords: 'auth/users/passwords'
                     }
  devise_scope :user do
    authenticated :user do
      root to: 'client/pages#dashboard', as: 'authenticated_user_root'
    end

    unauthenticated :user do
      root to: 'auth/users/sessions#new', as: 'unauthenticated_user_root'
    end
  end

  scope module: :client do
    resource  :account
    resources :items
    resources :link_specs,    only: [:show, :update]
    resources :offers,        only: [:index, :edit, :update]
    resources :messages,      only: [:new, :create]
    resources :conversations, only: [:index, :show, :destroy] do
      member do
        post :reply
        post :restore
        post :mark_as_read
      end
      collection do
        delete :empty_trash
      end
    end

    get 'dashboard', to: 'client/pages#dashboard'
  end

  namespace :storefront, path: 'spaces/:account_id' do
    resources :items,  only: [:show, :index]
    resources :offers, only: [:create]
  end

  # root to: 'client/pages#dashboard', as:
end

app/models/account.rb
class Account < ActiveRecord::Base
  has_many :users, dependent: :destroy
  has_many :items, dependent: :destroy
  has_many :offers, through: :items # account.offers.where('items.xx < ?', x)
  has_one  :social, dependent: :destroy
  accepts_nested_attributes_for :social

  has_attached_file :logo,
                    styles: { medium: '256x256>',
                              thumb: '60x60>',
                              large: '420x420>'},
                    default_url: ':style/placeholder_logo.png'

  validates_attachment_content_type :logo, content_type: /\Aimage\/.*\Z/
  # validates :name, presence: true


  after_create :create_social

  delegate :website, :facebook, :twitter, :instagram,
           to: :social, allow_nil: true


  private

  def create_social
    self.social = Social.create
  end
end

app/controllers/client/accounts_controller.rb
class Client::AccountsController < Client::BaseController
  respond_to :html, :json


  def edit
    respond_modal_with(current_account, location: authenticated_user_root_path)
  end


  def update
    if current_account.update_attributes(account_params)
      flash[:notice] = 'Account updated successfully.'
    else
      flash[:error] = current_account.errors.full_messages
    end
    redirect_to account_path
  end

  private

  def account_params
    # params.require(:account).permit!
    params.require(:account)
          .permit(:name,
                  :logo,
                  social_attributes:
                  [
                    :website,
                    :facebook,
                    :twitter,
                    :instagram
                  ])
  end
end

app/controllers/client/base_controller.rb
class Client::BaseController < ApplicationController
  before_filter :authenticate_user!

  helper_method :current_account

  layout 'client'

  def current_account
    @account ||= current_user.account
  end
end

app/controllers/client/conversations_controller.rb
class Client::ConversationsController < Client::BaseController
  before_action :get_mailbox
  before_action :get_conversation, except: [:index, :empty_trash]
  before_action :get_box, only: [:index]


  def index
    if @box.eql? "inbox"
      @conversations = @mailbox.inbox
    elsif @box.eql? "sent"
      @conversations = @mailbox.sentbox
    else
      @conversations = @mailbox.trash
    end

    @conversations = @conversations.paginate(page: params[:page], per_page: 10)
  end


  def show

  end


  def destroy
    @conversation.move_to_trash(current_user)
    flash[:success] = 'The conversation was moved to trash.'
    redirect_to conversations_path
  end


  def reply
    current_user.reply_to_conversation(@conversation, params[:body])
    flash[:success] = 'Reply sent'
    redirect_to conversation_path(@conversation)
  end


  def restore
    @conversation.untrash(current_user)
    flash[:success] = 'The conversation was restored.'
    redirect_to conversations_path
  end


  def empty_trash
    @mailbox.trash.each do |conversation|
      conversation.receipts_for(current_user).update_all(deleted: true)
    end
    flash[:success] = 'Your trash was cleaned!'
    redirect_to conversations_path
  end


  def mark_as_read
    @conversation.mark_as_read(current_user)
    flash[:success] = 'The conversation was marked as read.'
    redirect_to conversations_path
  end

  private

  def get_mailbox
    @mailbox ||= current_user.mailbox
  end


  def get_conversation
    @conversation ||= @mailbox.conversations.find(params[:id])
  end


  def get_box
    if params[:box].blank? or !["inbox","sent","trash"].include?(params[:box])
      params[:box] = 'inbox'
    end
    @box = params[:box]
  end
end

app/controllers/client/items_controller.rb
class Client::ItemsController < Client::BaseController
  respond_to :html, :json


  def index
    @items = current_account.items
                            .paginate(page: params[:page])
                            .per_page(20)
                            .order(created_at: :desc)
  end


  def show
    @item = current_account.items.find(params[:id])
    @offers = @item.offers.order(created_at: :desc)
    @accepted_offers = @item.accepted_offers
  end


  def new
    @item = current_account.items.new
    respond_modal_with @item
  end


  def create
    @item = current_account.items.new(item_params)
    if @item.save
      flash[:success] = 'Item added successfully.'
      redirect_to @item
    else
      flash[:error] = @item.errors.full_messages
      redirect_to items_url
    end
  end


  def edit
    @item = current_account.items.find(params[:id])
    respond_modal_with @item
  end


  def update
    @item = current_account.items.find(params[:id])
    if @item.update_attributes(item_params)
      flash[:success] = 'Item updated successfully.'
    else
      flash[:error] = @item.errors.full_messages
    end
    redirect_to @item
  end


  def destroy
    item = current_account.items.find(params[:id])
    item.destroy
    flash[:success] = 'Item has been removed'
    redirect_to items_url
  end


  private

  def item_params
    params.require(:item).permit(:uid,
                                 :name,
                                 :unit_price,
                                 :active,
                                 :listing_url,
                                 :image)
  end
end

app/controllers/client/link_specs_controller.rb
class Client::LinkSpecsController < Client::BaseController
  respond_to :html, :json


  def show
    @link_spec = LinkSpec.find(params[:id])
    @link = @link_spec.send(params[:link])

    respond_modal_with @link
  end


  def update
    @platform  = params[:platform]

    @link_spec = LinkSpec.find(params[:id])
    @link_spec.generate_link @platform

    respond_to do |format|
      format.js
    end
  end
end

app/controllers/client/messages_controller.rb
class Client::MessagesController < Client::BaseController
  def new
  end


  def create
    recipients = User.where(id: params['recipients'])
    conversation = current_user.send_message(recipients, params[:message][:body], params[:message][:subject]).conversation
    flash[:success] = "Message has been sent!"
    redirect_to conversation_path(conversation)
  end
end

app/controllers/client/offers_controller.rb
class Client::OffersController < Client::BaseController
  respond_to :html, :json

  def index
    @offers = current_account.offers
                             .paginate(page: params[:page])
                             .per_page(25)
                             .order(created_at: :desc)
  end


  def edit
    @offer = current_account.offers.find(params[:id])
    respond_modal_with @offer, location: authenticated_user_root_path
  end


  def update
    @offer = current_account.offers.find(params[:id])
    if @offer.update_attributes(offer_params)
      flash[:success] = 'Offer updated'
    else
      flash[:error] = @offer.errors.full_messages
    end
    redirect_to @offer.item
  end


  private

  def offer_params
    params.require(:offer).permit(:status)
  end
end

app/controllers/client/pages_controller.rb
class Client::PagesController < Client::BaseController
  def dashboard
    @latest_items  = current_account.items.order(created_at: :desc).limit(5)
    @latest_offers = current_account.offers.order(created_at: :desc).limit(5)
  end
end

app/helpers/client/accounts_helper.rb
module Client::AccountsHelper
end

app/helpers/client/conversations_helper.rb
module Client::ConversationsHelper
  def mailbox_section(title, current_box, opts = {})
    icon = opts.fetch(:icon, '')
    opts[:class] = opts.fetch(:class, '')
    opts[:class] += ' active' if title.downcase == current_box
    content_tag :li,
                link_to("<i class='fa fa-#{icon}' style='margin-right:10px'></i>#{title.capitalize}".html_safe,
                             conversations_path(box: title.downcase)), opts
  end
end

app/helpers/client/items_helper.rb
module Client::ItemsHelper
end

app/helpers/client/link_specs_helper.rb
module Client::LinkSpecsHelper
end

app/helpers/client/messages_helper.rb
module Client::MessagesHelper
  def recipients_options
    s = ''
    User.all.each do |user|
      s << "<option value='#{user.id}'>#{user.first_name}</option>"
    end
    s.html_safe
  end
end

app/helpers/client/offers_helper.rb
module Client::OffersHelper
end

app/helpers/client/pages_helper.rb
module Client::PagesHelper
end

app/views/client/accounts/edit.html.erb
<% content_for :title do %>
         Edit Account...
<% end %>

<%= simple_form_for current_account,
                  html: { data: { modal: true },
                          class: 'form-horizontal',
                          role: "form" } do |f| %>
  <div class="modal-body">
    <div class="box-body">

      <div class="row">
        <br/>

        <div class="col-md-12">
          <div class="form-group">
            <label class="control-label col-md-3">Name</label>
            <div class="col-md-9 input-group">
              <%= f.input_field :name, as: 'string', label: false, class: "form-control col-md-10" %>
            </div>
          </div>
        </div>

        <div class="col-md-12">
          <div class="form-group">
            <label class="control-label col-md-3">Logo</label>
            <div class="col-md-9 input-group">
              <%= f.input :logo, as: :file, label: false %>
              <p class="help-block"><small>Upload an image for your logo</small></p>
            </div>
          </div>
        </div>

        <%= f.simple_fields_for :social  do |soc| %>
            <div class="col-md-12">
              <div class="form-group">
                <label class="control-label col-md-3">Website/Blog</label>
                <div class="col-md-9 input-group">
                  <span class="input-group-addon"><small>http://</small></span>
                  <%= soc.input_field :website, as: 'string', label: false, class: "form-control col-md-10" %>
                </div>
              </div>
            </div>
            <div class="col-md-12">
              <div class="form-group">
                <label class="control-label col-md-3">Facebook</label>
                <div class="col-md-9 input-group">
                  <span class="input-group-addon"><small>http://</small></span>
                  <%= soc.input_field :facebook, as: 'string', label: false, class: "form-control col-md-10" %>
                </div>
              </div>
            </div>
            <div class="col-md-12">
              <div class="form-group">
                <label class="control-label col-md-3">Twitter</label>
                <div class="col-md-9 input-group">
                  <span class="input-group-addon"><small>http://</small></span>
                  <%= soc.input_field :twitter, as: 'string', label: false, class: "form-control col-md-10" %>
                </div>
              </div>
            </div>
            <div class="col-md-12">
              <div class="form-group">
                <label class="control-label col-md-3">Instagram</label>
                <div class="col-md-9 input-group">
                  <span class="input-group-addon"><small>http://</small></span>
                  <%= soc.input_field :instagram, as: 'string', label: false, class: "form-control col-md-10" %>
                </div>
              </div>
            </div>
        <% end  %>


        <!--
        <%# Incase I add an account image later  %>
        <div class="col-md-12">
          <div class="form-group">
            <label>Instagram</label>
            <%#= f.input :image, as: :file, label: false %>
            <p class="help-block">Upload an image for the item </p>
          </div>
        </div>
        -->

      </div>
    </div><!-- /.box-body -->
  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-default pull-left" data-dismiss="modal">
      Close
    </button>
    <%= f.submit "Save", class: "btn btn-primary" %>
  </div>
<% end -%>

app/views/client/accounts/show.html.erb
<% content_for :title do %>
    Settings
<% end %>

<% content_for :section_header_big do %>
    Settings
<% end %>

<% content_for :section_header_small do %>
    Manage your settings
<% end %>

<% content_for :styles do %>
    .form-horizontal .control-label {
        text-align: inherit;
    }
    .text-field {
        padding-top:7px;
    }
<% end %>

<div class="row">
  <div class="col-md-6">
    <!-- jQuery Knob -->
    <div class="box">
      <div class="box-header">
        <i class="fa fa-cogs"></i>
        <h3 class="box-title">Account</h3>
        <div class="box-tools pull-right">
          <div class="btn-group">
            <button class="btn btn-box-tool dropdown-toggle" data-toggle="dropdown" aria-expanded="false"><i class="fa fa-wrench"></i></button>
            <ul class="dropdown-menu" role="menu">
              <li>
                <%= link_to "Edit", edit_account_path, data: { modal: true } %>
              </li>
              <!-- <li class="divider"></li>
              <li><a href="#">Separated link</a></li> -->
            </ul>
          </div>
        </div>
      </div><!-- /.box-header -->

      <div class="box-body">
        <div class="row">
          <div class="col-md-12" style="padding-left:20px;">
            <form class="form-horizontal">
              <div class="form-group">
                <label for="" class="control-label col-xs-4">Account Name</label>
                <div class="col-xs-8">
                  <p class="text-field"><%= current_account.name %></p>
                </div>
              </div>
              <div class="form-group">
                <label for="" class="control-label col-xs-4">Logo</label>
                <div class="col-xs-8">
                  <%= image_tag current_account.logo.url(:thumb),
                                style: 'width:50px;height:50px;',
                                class: 'img-circle'%>
                </div>
              </div>
              <div class="form-group">
                <label for="" class="control-label col-xs-4">Website</label>
                <div class="col-xs-8">
                  <p class="text-field"><%= current_account.social.website.presence || 'Not Set'  %></p>
                </div>
              </div>
              <div class="form-group">
                <label for="" class="control-label col-xs-4">Facebook</label>
                <div class="col-xs-8">
                  <p class="text-field"><%= current_account.social.facebook.presence || 'Not Set'  %></p>
                </div>
              </div>
              <div class="form-group">
                <label for="" class="control-label col-xs-4">Twitter</label>
                <div class="col-xs-8">
                  <p class="text-field"><%= current_account.social.twitter.presence || 'Not Set' %></p>
                </div>
              </div>
              <div class="form-group">
                <label for="" class="control-label col-xs-4">Instagram</label>
                <div class="col-xs-8">
                  <p class="text-field"><%= current_account.social.instagram.presence || 'Not Set' %></p>
                </div>
              </div>
            </form>
          </div>
        </div><!-- /.row -->
      </div><!-- /.box-body -->
    </div><!-- /.box -->
  </div><!-- /.col -->

  <div class="col-md-6">
      <!-- jQuery Knob -->
      <div class="box">
        <div class="box-header">
          <i class="fa fa-user"></i>
          <h3 class="box-title">Profile</h3>
          <div class="box-tools pull-right">
            <div class="btn-group">
              <button class="btn btn-box-tool dropdown-toggle" data-toggle="dropdown" aria-expanded="false"><i class="fa fa-wrench"></i></button>
              <ul class="dropdown-menu" role="menu">
                <li>
                  <%= link_to "Edit", edit_user_registration_path,
                              remote: request.xhr?,
                              data: { modal: true } %>
                </li>
                <!-- <li class="divider"></li>
                <li><a href="#">Separated link</a></li> -->
              </ul>
            </div>
          </div>
        </div><!-- /.box-header -->

        <div class="box-body">
          <div class="row">
            <div class="col-md-12" style="padding-left:20px;">
              <form class="form-horizontal">
                <div class="form-group">
                  <label for="" class="control-label col-xs-4">First Name</label>
                  <div class="col-xs-8">
                    <p class="text-field"><%= current_user.first_name %></p>
                  </div>
                </div>
                <div class="form-group">
                  <label for="" class="control-label col-xs-4">Last Name</label>
                  <div class="col-xs-8">
                    <p class="text-field"><%= current_user.last_name  %></p>
                  </div>
                </div>
                <div class="form-group">
                  <label for="" class="control-label col-xs-4">Email</label>
                  <div class="col-xs-8">
                    <p class="text-field"><%= current_user.email %></p>
                  </div>
                </div>
                <div class="form-group">
                  <label for="" class="control-label col-xs-4">Password</label>
                  <div class="col-xs-8">
                    <p class="text-field">**********</p>
                  </div>
                </div>
              </form>
            </div>
          </div><!-- /.row -->
        </div><!-- /.box-body -->
      </div><!-- /.box -->
    </div><!-- /.col -->
</div><!-- /.row -->