config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
                       sessions: 'auth/users/sessions' ,
                       registrations: 'auth/users/registrations',
                       passwords: 'auth/users/passwords'
                     }
  devise_scope :user do
    authenticated :user do
      root to: 'client/pages#dashboard', as: 'authenticated_user_root'
    end

    unauthenticated :user do
      root to: 'auth/users/sessions#new', as: 'unauthenticated_user_root'
    end
  end

  scope module: :client do
    resource  :account
    resources :items
    resources :link_specs,    only: [:show, :update]
    resources :offers,        only: [:index, :edit, :update]
    resources :messages,      only: [:new, :create]
    resources :conversations, only: [:index, :show, :destroy] do
      member do
        post :reply
        post :restore
        post :mark_as_read
      end
      collection do
        delete :empty_trash
      end
    end

    get 'dashboard', to: 'client/pages#dashboard'
  end

  namespace :storefront, path: 'spaces/:account_id' do
    resources :items,  only: [:show, :index]
    resources :offers, only: [:create]
  end

  # root to: 'client/pages#dashboard', as:
end

app/controllers/client/accounts_controller.rb
class Client::AccountsController < Client::BaseController
  respond_to :html, :json


  def edit
    respond_modal_with(current_account, location: authenticated_user_root_path)
  end


  def update
    if current_account.update_attributes(account_params)
      flash[:notice] = 'Account updated successfully.'
    else
      flash[:error] = current_account.errors.full_messages
    end
    redirect_to account_path
  end

  private

  def account_params
    # params.require(:account).permit!
    params.require(:account)
          .permit(:name,
                  :logo,
                  social_attributes:
                  [
                    :website,
                    :facebook,
                    :twitter,
                    :instagram
                  ])
  end
end

app/controllers/client/base_controller.rb
class Client::BaseController < ApplicationController
  before_filter :authenticate_user!

  helper_method :current_account

  layout 'client'

  def current_account
    @account ||= current_user.account
  end
end

app/controllers/client/conversations_controller.rb
class Client::ConversationsController < Client::BaseController
  before_action :get_mailbox
  before_action :get_conversation, except: [:index, :empty_trash]
  before_action :get_box, only: [:index]


  def index
    if @box.eql? "inbox"
      @conversations = @mailbox.inbox
    elsif @box.eql? "sent"
      @conversations = @mailbox.sentbox
    else
      @conversations = @mailbox.trash
    end

    @conversations = @conversations.paginate(page: params[:page], per_page: 10)
  end


  def show

  end


  def destroy
    @conversation.move_to_trash(current_user)
    flash[:success] = 'The conversation was moved to trash.'
    redirect_to conversations_path
  end


  def reply
    current_user.reply_to_conversation(@conversation, params[:body])
    flash[:success] = 'Reply sent'
    redirect_to conversation_path(@conversation)
  end


  def restore
    @conversation.untrash(current_user)
    flash[:success] = 'The conversation was restored.'
    redirect_to conversations_path
  end


  def empty_trash
    @mailbox.trash.each do |conversation|
      conversation.receipts_for(current_user).update_all(deleted: true)
    end
    flash[:success] = 'Your trash was cleaned!'
    redirect_to conversations_path
  end


  def mark_as_read
    @conversation.mark_as_read(current_user)
    flash[:success] = 'The conversation was marked as read.'
    redirect_to conversations_path
  end

  private

  def get_mailbox
    @mailbox ||= current_user.mailbox
  end


  def get_conversation
    @conversation ||= @mailbox.conversations.find(params[:id])
  end


  def get_box
    if params[:box].blank? or !["inbox","sent","trash"].include?(params[:box])
      params[:box] = 'inbox'
    end
    @box = params[:box]
  end
end

app/controllers/client/items_controller.rb
class Client::ItemsController < Client::BaseController
  respond_to :html, :json


  def index
    @items = current_account.items
                            .paginate(page: params[:page])
                            .per_page(20)
                            .order(created_at: :desc)
  end


  def show
    @item = current_account.items.find(params[:id])
    @offers = @item.offers.order(created_at: :desc)
    @accepted_offers = @item.accepted_offers
  end


  def new
    @item = current_account.items.new
    respond_modal_with @item
  end


  def create
    @item = current_account.items.new(item_params)
    if @item.save
      flash[:success] = 'Item added successfully.'
      redirect_to @item
    else
      flash[:error] = @item.errors.full_messages
      redirect_to items_url
    end
  end


  def edit
    @item = current_account.items.find(params[:id])
    respond_modal_with @item
  end


  def update
    @item = current_account.items.find(params[:id])
    if @item.update_attributes(item_params)
      flash[:success] = 'Item updated successfully.'
    else
      flash[:error] = @item.errors.full_messages
    end
    redirect_to @item
  end


  def destroy
    item = current_account.items.find(params[:id])
    item.destroy
    flash[:success] = 'Item has been removed'
    redirect_to items_url
  end


  private

  def item_params
    params.require(:item).permit(:uid,
                                 :name,
                                 :unit_price,
                                 :active,
                                 :listing_url,
                                 :image)
  end
end

app/controllers/client/link_specs_controller.rb
class Client::LinkSpecsController < Client::BaseController
  respond_to :html, :json


  def show
    @link_spec = LinkSpec.find(params[:id])
    @link = @link_spec.send(params[:link])

    respond_modal_with @link
  end


  def update
    @platform  = params[:platform]

    @link_spec = LinkSpec.find(params[:id])
    @link_spec.generate_link @platform

    respond_to do |format|
      format.js
    end
  end
end

app/controllers/client/messages_controller.rb
class Client::MessagesController < Client::BaseController
  def new
  end


  def create
    recipients = User.where(id: params['recipients'])
    conversation = current_user.send_message(recipients, params[:message][:body], params[:message][:subject]).conversation
    flash[:success] = "Message has been sent!"
    redirect_to conversation_path(conversation)
  end
end

app/controllers/client/offers_controller.rb
class Client::OffersController < Client::BaseController
  respond_to :html, :json

  def index
    @offers = current_account.offers
                             .paginate(page: params[:page])
                             .per_page(25)
                             .order(created_at: :desc)
  end


  def edit
    @offer = current_account.offers.find(params[:id])
    respond_modal_with @offer, location: authenticated_user_root_path
  end


  def update
    @offer = current_account.offers.find(params[:id])
    if @offer.update_attributes(offer_params)
      flash[:success] = 'Offer updated'
    else
      flash[:error] = @offer.errors.full_messages
    end
    redirect_to @offer.item
  end


  private

  def offer_params
    params.require(:offer).permit(:status)
  end
end

app/controllers/client/pages_controller.rb
class Client::PagesController < Client::BaseController
  def dashboard
    @latest_items  = current_account.items.order(created_at: :desc).limit(5)
    @latest_offers = current_account.offers.order(created_at: :desc).limit(5)
  end
end

app/helpers/client/accounts_helper.rb
module Client::AccountsHelper
end

app/helpers/client/conversations_helper.rb
module Client::ConversationsHelper
  def mailbox_section(title, current_box, opts = {})
    icon = opts.fetch(:icon, '')
    opts[:class] = opts.fetch(:class, '')
    opts[:class] += ' active' if title.downcase == current_box
    content_tag :li,
                link_to("<i class='fa fa-#{icon}' style='margin-right:10px'></i>#{title.capitalize}".html_safe,
                             conversations_path(box: title.downcase)), opts
  end
end

app/helpers/client/items_helper.rb
module Client::ItemsHelper
end

app/helpers/client/link_specs_helper.rb
module Client::LinkSpecsHelper
end

app/helpers/client/messages_helper.rb
module Client::MessagesHelper
  def recipients_options
    s = ''
    User.all.each do |user|
      s << "<option value='#{user.id}'>#{user.first_name}</option>"
    end
    s.html_safe
  end
end

app/helpers/client/offers_helper.rb
module Client::OffersHelper
end

app/helpers/client/pages_helper.rb
module Client::PagesHelper
end

app/views/client/conversations/_conversation.html.erb
<% if false %>
    <li class="list-group-item clearfix">
      <%= link_to conversation.subject, conversation_path(conversation) %>

      <div class="btn-group-vertical pull-right">
        <% if conversation.is_trashed?(current_user) %>
            <%= link_to 'Restore', restore_conversation_path(conversation), class: 'btn btn-xs btn-info', method: :post %>
        <% else %>
            <%= link_to 'Move to trash', conversation_path(conversation), class: 'btn btn-xs btn-danger', method: :delete,
                        data: {confirm: 'Are you sure?'} %>
            <% if conversation.is_unread?(current_user) %>
                <%= link_to 'Mark as read', mark_as_read_conversation_path(conversation),
                            class: 'btn btn-xs btn-info', method: :post %>
            <% end %>
        <% end %>
      </div>

      <p><%= render 'client/conversations/participants', conversation: conversation %></p>

      <p><%= conversation.last_message.body %>
        <small>(<span class="text-muted"><%= conversation.last_message.created_at.strftime("%-d %B %Y, %H:%M:%S") %></span>)</small></p>
    </li>
<% end %>

<tr>
  <td><div class="icheckbox_flat-blue" aria-checked="false" aria-disabled="false" style="position: relative;">
    <input type="checkbox" style="position: absolute; opacity: 0;">
    <ins class="iCheck-helper" style="position: absolute; top: 0%; left: 0%; display: block; width: 100%; height: 100%; margin: 0px; padding: 0px; border: 0px; opacity: 0; background: rgb(255, 255, 255);"></ins></div></td>
  <td class="mailbox-star"><a href="#"><i class="fa fa-star-o text-yellow"></i></a></td>
  <td class="mailbox-name">
    <%= link_to conversation.participants.first.name, conversation_path(conversation) %>
  </td>
  <td class="mailbox-subject"><b><%= conversation.subject %></b> - <%= truncate(conversation.last_message.body) %></td>
  <!-- <td class="mailbox-attachment"></td> -->
  <td class="mailbox-date"><%= time_ago_in_words(conversation.created_at) %></td>
</tr>

app/views/client/conversations/_folders.html.erb
<div class="col-md-3">
  <%= link_to 'Compose', new_message_path, class: 'btn btn-primary btn-block margin-bottom' %>
  <div class="box box-solid">
    <div class="box-header with-border">
      <h3 class="box-title">Folders</h3>
    </div>
    <div class="box-body no-padding">
      <ul class="nav nav-pills nav-stacked">
        <%= mailbox_section 'inbox', @box, icon: 'inbox' %>
        <%= mailbox_section 'sent', @box, icon: 'envelope-o' %>
        <%= mailbox_section 'trash', @box, icon: 'trash-o' %>
      </ul>
    </div><!-- /.box-body -->
  </div><!-- /. box -->
</div><!-- /.col -->

app/views/client/conversations/_participants.html.erb
<% conversation.participants.each do |participant| %>
    <% unless participant == current_user %>
        <%#= gravatar_for participant %>
    <% end %>
<% end %>

app/views/client/conversations/index.html.erb
<% if false %>
    <div class="row">
      <div class="col-sm-9">
        <% if @box == 'trash' %>
            <p><%= link_to 'Empty trash', empty_trash_conversations_path, class: 'btn btn-danger', method: :delete,
                           data: {confirm: 'Are you sure?'} %></p>
        <% end %>
        <ul class="list-group">
          <%= render partial: 'client/conversations/conversation', collection: @conversations %>
        </ul>
        <%= will_paginate %>
      </div>
    </div>
<% end %>

<% content_for :title do %>
    Mailbox
<% end %>

<% content_for :section_header_big do %>
    Mailbox
<% end %>

<% content_for :section_header_small do %>
    0 new messages
<% end %>

  <div class="row">
    <%= render partial: 'client/conversations/folders' %>

    <div class="col-md-9">
      <div class="box box-primary">
        <div class="box-header with-border">
          <h3 class="box-title">Inbox</h3>
          <div class="box-tools pull-right">
            <div class="has-feedback">
              <input type="text" class="form-control input-sm" placeholder="Search Mail">
              <span class="glyphicon glyphicon-search form-control-feedback"></span>
            </div>
          </div><!-- /.box-tools -->
        </div><!-- /.box-header -->
        <div class="box-body no-padding">
          <div class="mailbox-controls">
            &nbsp;
          </div>
          <div class="table-responsive mailbox-messages">
            <table class="table table-hover table-striped">
              <tbody>
              <%= render partial: 'client/conversations/conversation', collection: @conversations %>
              </tbody>
            </table><!-- /.table -->
          </div><!-- /.mail-box-messages -->
        </div><!-- /.box-body -->
        <div class="box-footer no-padding">
          <div class="mailbox-controls">
            &nbsp;
          </div>
        </div>
      </div><!-- /. box -->
    </div><!-- /.col -->
  </div><!-- /.row -->

app/views/client/conversations/show.html.erb
<% content_for :styles do %>
    .messages {
    max-height: 400px;
    overflow-y: auto;
    margin-bottom: 1em;
    margin-top: 1em;
    }
<% end %>

<!--
<p>Chatting with
  <%#= render 'client/conversations/participants', conversation: @conversation %>
</p>

<div class="panel panel-default">
  <div class="panel-heading"><%#= @conversation.subject %></div>

  <div class="panel-body">
    <div class="messages">
      <%# @conversation.receipts_for(current_user).each do |receipt| %>
          <div class="media">
            <%# message = receipt.message %>
            <div class="media-left">
              <%#= gravatar_for message.sender, 45, message.sender.name %>
            </div>

            <div class="media-body">
              <h6 class="media-heading"><%#= message.sender.name %>
                says at <%#= message.created_at.strftime("%-d %B %Y, %H:%M:%S") %></h6>
              <%#= message.body %>
            </div>
          </div>
      <%# end %>
    </div>
  </div>
</div>
-->

<% content_for :title do %>
    Mailbox
<% end %>

<% content_for :section_header_big do %>
    Mailbox
<% end %>

<% content_for :section_header_small do %>
    Conversation with James
<% end %>

<div class="row">
  <%= render partial: 'client/conversations/folders' %>

  <div class="col-md-9">
    <!-- DIRECT CHAT -->
    <div id="myDirectChat" class="box box-primary" style="min-height:500px">
      <div class="box-header with-border">
        <h3 class="box-title"> <%= @conversation.subject %> </h3>
      </div><!-- /.box-header -->
      <div class="box-body" style="min-height:500px;">
        <!-- Conversations are loaded here -->
        <div class="direct-chat-messages" style="min-height: 500px;">

          <% @conversation.receipts_for(current_user).each do |receipt| %>
              <% message = receipt.message %>
              <% message_owner = message.sender == current_user%>

              <div class="direct-chat-msg <%= 'right' if message_owner %>">
                <div class="direct-chat-info clearfix">
                  <span class="direct-chat-name pull-left"><%= message.sender.name %></span>
                  <span class="direct-chat-timestamp pull-right">
                    <%= message.created_at.strftime("%-d %B %l:%M %p") %>
                  </span>
                </div><!-- /.direct-chat-info -->
                <img class="direct-chat-img" src="dist/img/user1-128x128.jpg" alt="message user image"><!-- /.direct-chat-img -->
                <div class="direct-chat-text">
                  <%= message.body %>
                </div><!-- /.direct-chat-text -->
              </div><!-- /.direct-chat-msg -->
          <% end %>
        </div><!--/.direct-chat-messages-->


        <!-- Contacts are loaded here -->
        <div class="direct-chat-contacts">
          <ul class="contacts-list">
            <li>
              <a href="#">
                <img class="contacts-list-img" src="dist/img/user1-128x128.jpg">
                <div class="contacts-list-info">
                            <span class="contacts-list-name">
                              Count Dracula
                              <small class="contacts-list-date pull-right">2/28/2015</small>
                            </span>
                  <span class="contacts-list-msg">How have you been? I was...</span>
                </div><!-- /.contacts-list-info -->
              </a>
            </li><!-- End Contact Item -->
            <li>
              <a href="#">
                <img class="contacts-list-img" src="dist/img/user7-128x128.jpg">
                <div class="contacts-list-info">
                            <span class="contacts-list-name">
                              Sarah Doe
                              <small class="contacts-list-date pull-right">2/23/2015</small>
                            </span>
                  <span class="contacts-list-msg">I will be waiting for...</span>
                </div><!-- /.contacts-list-info -->
              </a>
            </li><!-- End Contact Item -->
            <li>
              <a href="#">
                <img class="contacts-list-img" src="dist/img/user3-128x128.jpg">
                <div class="contacts-list-info">
                            <span class="contacts-list-name">
                              Nadia Jolie
                              <small class="contacts-list-date pull-right">2/20/2015</small>
                            </span>
                  <span class="contacts-list-msg">I'll call you back at...</span>
                </div><!-- /.contacts-list-info -->
              </a>
            </li><!-- End Contact Item -->
            <li>
              <a href="#">
                <img class="contacts-list-img" src="dist/img/user5-128x128.jpg">
                <div class="contacts-list-info">
                            <span class="contacts-list-name">
                              Nora S. Vans
                              <small class="contacts-list-date pull-right">2/10/2015</small>
                            </span>
                  <span class="contacts-list-msg">Where is your new...</span>
                </div><!-- /.contacts-list-info -->
              </a>
            </li><!-- End Contact Item -->
            <li>
              <a href="#">
                <img class="contacts-list-img" src="dist/img/user6-128x128.jpg">
                <div class="contacts-list-info">
                            <span class="contacts-list-name">
                              John K.
                              <small class="contacts-list-date pull-right">1/27/2015</small>
                            </span>
                  <span class="contacts-list-msg">Can I take a look at...</span>
                </div><!-- /.contacts-list-info -->
              </a>
            </li><!-- End Contact Item -->
            <li>
              <a href="#">
                <img class="contacts-list-img" src="dist/img/user8-128x128.jpg">
                <div class="contacts-list-info">
                            <span class="contacts-list-name">
                              Kenneth M.
                              <small class="contacts-list-date pull-right">1/4/2015</small>
                            </span>
                  <span class="contacts-list-msg">Never mind I found...</span>
                </div><!-- /.contacts-list-info -->
              </a>
            </li><!-- End Contact Item -->
          </ul><!-- /.contatcts-list -->
        </div><!-- /.direct-chat-pane -->
      </div><!-- /.box-body -->
      <div class="box-footer">
        <%= form_tag reply_conversation_path(@conversation), method: :post do %>
            <div class="input-group">
              <%= text_field_tag 'body', nil, class: 'form-control', placeholder: 'Type message...', required: true %>
              <span class="input-group-btn">
                <%= submit_tag "Send", class: 'btn btn-flat' %>
              </span>
            </div>
        <% end %>


      </div><!-- /.box-footer-->
    </div><!--/.direct-chat -->
  </div>
</div>