config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
                       sessions: 'auth/users/sessions' ,
                       registrations: 'auth/users/registrations',
                       passwords: 'auth/users/passwords'
                     }
  devise_scope :user do
    authenticated :user do
      root to: 'client/pages#dashboard', as: 'authenticated_user_root'
    end

    unauthenticated :user do
      root to: 'auth/users/sessions#new', as: 'unauthenticated_user_root'
    end
  end

  scope module: :client do
    resource  :account
    resources :items
    resources :link_specs,    only: [:show, :update]
    resources :offers,        only: [:index, :edit, :update]
    resources :messages,      only: [:new, :create]
    resources :conversations, only: [:index, :show, :destroy] do
      member do
        post :reply
        post :restore
        post :mark_as_read
      end
      collection do
        delete :empty_trash
      end
    end

    get 'dashboard', to: 'client/pages#dashboard'
  end

  namespace :storefront, path: 'spaces/:account_id' do
    resources :items,  only: [:show, :index]
    resources :offers, only: [:create]
  end

  # root to: 'client/pages#dashboard', as:
end

app/controllers/client/accounts_controller.rb
class Client::AccountsController < Client::BaseController
  respond_to :html, :json


  def edit
    respond_modal_with(current_account, location: authenticated_user_root_path)
  end


  def update
    if current_account.update_attributes(account_params)
      flash[:notice] = 'Account updated successfully.'
    else
      flash[:error] = current_account.errors.full_messages
    end
    redirect_to account_path
  end

  private

  def account_params
    # params.require(:account).permit!
    params.require(:account)
          .permit(:name,
                  :logo,
                  social_attributes:
                  [
                    :website,
                    :facebook,
                    :twitter,
                    :instagram
                  ])
  end
end

app/controllers/client/base_controller.rb
class Client::BaseController < ApplicationController
  before_filter :authenticate_user!

  helper_method :current_account

  layout 'client'

  def current_account
    @account ||= current_user.account
  end
end

app/controllers/client/conversations_controller.rb
class Client::ConversationsController < Client::BaseController
  before_action :get_mailbox
  before_action :get_conversation, except: [:index, :empty_trash]
  before_action :get_box, only: [:index]


  def index
    if @box.eql? "inbox"
      @conversations = @mailbox.inbox
    elsif @box.eql? "sent"
      @conversations = @mailbox.sentbox
    else
      @conversations = @mailbox.trash
    end

    @conversations = @conversations.paginate(page: params[:page], per_page: 10)
  end


  def show

  end


  def destroy
    @conversation.move_to_trash(current_user)
    flash[:success] = 'The conversation was moved to trash.'
    redirect_to conversations_path
  end


  def reply
    current_user.reply_to_conversation(@conversation, params[:body])
    flash[:success] = 'Reply sent'
    redirect_to conversation_path(@conversation)
  end


  def restore
    @conversation.untrash(current_user)
    flash[:success] = 'The conversation was restored.'
    redirect_to conversations_path
  end


  def empty_trash
    @mailbox.trash.each do |conversation|
      conversation.receipts_for(current_user).update_all(deleted: true)
    end
    flash[:success] = 'Your trash was cleaned!'
    redirect_to conversations_path
  end


  def mark_as_read
    @conversation.mark_as_read(current_user)
    flash[:success] = 'The conversation was marked as read.'
    redirect_to conversations_path
  end

  private

  def get_mailbox
    @mailbox ||= current_user.mailbox
  end


  def get_conversation
    @conversation ||= @mailbox.conversations.find(params[:id])
  end


  def get_box
    if params[:box].blank? or !["inbox","sent","trash"].include?(params[:box])
      params[:box] = 'inbox'
    end
    @box = params[:box]
  end
end

app/controllers/client/items_controller.rb
class Client::ItemsController < Client::BaseController
  respond_to :html, :json


  def index
    @items = current_account.items
                            .paginate(page: params[:page])
                            .per_page(20)
                            .order(created_at: :desc)
  end


  def show
    @item = current_account.items.find(params[:id])
    @offers = @item.offers.order(created_at: :desc)
    @accepted_offers = @item.accepted_offers
  end


  def new
    @item = current_account.items.new
    respond_modal_with @item
  end


  def create
    @item = current_account.items.new(item_params)
    if @item.save
      flash[:success] = 'Item added successfully.'
      redirect_to @item
    else
      flash[:error] = @item.errors.full_messages
      redirect_to items_url
    end
  end


  def edit
    @item = current_account.items.find(params[:id])
    respond_modal_with @item
  end


  def update
    @item = current_account.items.find(params[:id])
    if @item.update_attributes(item_params)
      flash[:success] = 'Item updated successfully.'
    else
      flash[:error] = @item.errors.full_messages
    end
    redirect_to @item
  end


  def destroy
    item = current_account.items.find(params[:id])
    item.destroy
    flash[:success] = 'Item has been removed'
    redirect_to items_url
  end


  private

  def item_params
    params.require(:item).permit(:uid,
                                 :name,
                                 :unit_price,
                                 :active,
                                 :listing_url,
                                 :image)
  end
end

app/controllers/client/link_specs_controller.rb
class Client::LinkSpecsController < Client::BaseController
  respond_to :html, :json


  def show
    @link_spec = LinkSpec.find(params[:id])
    @link = @link_spec.send(params[:link])

    respond_modal_with @link
  end


  def update
    @platform  = params[:platform]

    @link_spec = LinkSpec.find(params[:id])
    @link_spec.generate_link @platform

    respond_to do |format|
      format.js
    end
  end
end

app/controllers/client/messages_controller.rb
class Client::MessagesController < Client::BaseController
  def new
  end


  def create
    recipients = User.where(id: params['recipients'])
    conversation = current_user.send_message(recipients, params[:message][:body], params[:message][:subject]).conversation
    flash[:success] = "Message has been sent!"
    redirect_to conversation_path(conversation)
  end
end

app/controllers/client/offers_controller.rb
class Client::OffersController < Client::BaseController
  respond_to :html, :json

  def index
    @offers = current_account.offers
                             .paginate(page: params[:page])
                             .per_page(25)
                             .order(created_at: :desc)
  end


  def edit
    @offer = current_account.offers.find(params[:id])
    respond_modal_with @offer, location: authenticated_user_root_path
  end


  def update
    @offer = current_account.offers.find(params[:id])
    if @offer.update_attributes(offer_params)
      flash[:success] = 'Offer updated'
    else
      flash[:error] = @offer.errors.full_messages
    end
    redirect_to @offer.item
  end


  private

  def offer_params
    params.require(:offer).permit(:status)
  end
end

app/controllers/client/pages_controller.rb
class Client::PagesController < Client::BaseController
  def dashboard
    @latest_items  = current_account.items.order(created_at: :desc).limit(5)
    @latest_offers = current_account.offers.order(created_at: :desc).limit(5)
  end
end

app/helpers/client/accounts_helper.rb
module Client::AccountsHelper
end

app/helpers/client/conversations_helper.rb
module Client::ConversationsHelper
  def mailbox_section(title, current_box, opts = {})
    icon = opts.fetch(:icon, '')
    opts[:class] = opts.fetch(:class, '')
    opts[:class] += ' active' if title.downcase == current_box
    content_tag :li,
                link_to("<i class='fa fa-#{icon}' style='margin-right:10px'></i>#{title.capitalize}".html_safe,
                             conversations_path(box: title.downcase)), opts
  end
end

app/helpers/client/items_helper.rb
module Client::ItemsHelper
end

app/helpers/client/link_specs_helper.rb
module Client::LinkSpecsHelper
end

app/helpers/client/messages_helper.rb
module Client::MessagesHelper
  def recipients_options
    s = ''
    User.all.each do |user|
      s << "<option value='#{user.id}'>#{user.first_name}</option>"
    end
    s.html_safe
  end
end

app/helpers/client/offers_helper.rb
module Client::OffersHelper
end

app/helpers/client/pages_helper.rb
module Client::PagesHelper
end

app/views/client/pages/dashboard.html.erb
<% content_for :title do %>
    Dashboard
<% end %>

<% content_for :section_header_big do %>
Dashboard
<% end %>

<% content_for :section_header_small do %>
    Control Panel
<% end %>

<% content_for :section_header_right do %>
    <%= render partial: 'client/items/add_item_button' %>
<% end %>


<div class="row">
  <div class="col-lg-3 col-md-3  col-xs-6">
    <!-- small box -->
    <div class="small-box bg-teal">
      <div class="inner">
        <h3><%= current_account.items.count %></h3>
        <p>Items</p>
      </div>
      <div class="icon">
        <i class="ion ion-bag"></i>
      </div>
      <a href="<%= items_url %>" class="small-box-footer">More info <i class="fa fa-arrow-circle-right"></i></a>
    </div>
  </div><!-- ./col -->
  <div class="col-lg-3 col-md-3 col-xs-6">
    <!-- small box -->
    <div class="small-box bg-green">
      <div class="inner">
        <h3><%= current_account.offers.count %></h3>
        <p>Pending Offers</p>
      </div>
      <div class="icon">
        <i class="ion ion-social-usd"></i>
      </div>
      <a href="<%= offers_url %>" class="small-box-footer">More info <i class="fa fa-arrow-circle-right"></i></a>
    </div>
  </div><!-- ./col -->
  <div class="col-lg-3 col-md-3  col-xs-6">
    <!-- small box -->
    <div class="small-box bg-maroon">
      <div class="inner">
        <h3>44</h3>
        <p>Customers</p>
      </div>
      <div class="icon">
        <i class="ion ion-person-add"></i>
      </div>
      <a href="#" class="small-box-footer">More info <i class="fa fa-arrow-circle-right"></i></a>
    </div>
  </div><!-- ./col -->
  <div class="col-lg-3 col-md-3  col-xs-6">
    <!-- small box -->
    <div class="small-box bg-purple">
      <div class="inner">
        <h3>65</h3>
        <p>Unique Visitors</p>
      </div>
      <div class="icon">
        <i class="ion ion-pie-graph"></i>
      </div>
      <a href="#" class="small-box-footer">More info <i class="fa fa-arrow-circle-right"></i></a>
    </div>
  </div><!-- ./col -->
</div><!-- /.row -->
<div class="row">
  <div class="col-md-8">
    <!-- TABLE: LATEST ORDERS -->
    <div class="box">
      <div class="box-header">
        <h3 class="box-title">Latest Offers</h3>
        <div class="box-tools pull-right">
          <button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
        </div>
      </div><!-- /.box-header -->

      <% if @latest_offers.present? %>
          <div class="box-body">
            <div class="table-responsive">
              <table class="table no-margin">
                <thead>
                <tr>
                  <th>Item</th>
                  <th>Original Price</th>
                  <th>Offer Price</th>
                  <th>Quantity</th>
                </tr>
                </thead>
                <tbody>

                <% @latest_offers.each do |offer| %>
                    <tr>
                      <td><%= link_to truncate(offer.item.name), item_path(offer.item) %></td>
                      <td><%= humanized_money_with_symbol offer.item.unit_price %></td>
                      <td><%= humanized_money_with_symbol offer.amount  %></td>
                      <td><%= offer.quantity %></td>
                    </tr>
                <% end %>
                </tbody>
              </table>
            </div><!-- /.table-responsive -->
          </div><!-- /.box-body -->
          <div class="box-footer text-center">
            <%= link_to 'View All Offers', offers_url, class: 'uppercase' %>
          </div><!-- /.box-footer -->
      <% else %>
          <div class="col-md-12 text-center" style="padding-top:30px;">
            <p class="lead">
              No offers made
            </p>
          </div>
          <div class="box-footer text-center">
            &nbsp;
          </div><!-- /.box-footer -->
      <% end %>




    </div><!-- /.box -->
  </div><!-- /.col -->
  <div class="col-md-4">
    <!-- PRODUCT LIST -->
    <div class="box">
      <div class="box-header with-border">
        <h3 class="box-title">Recently Added Items</h3>
        <div class="box-tools pull-right">
          <button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
        </div>
      </div><!-- /.box-header -->


        <% if @latest_items.present? %>
          <div class="box-body">
            <ul class="products-list product-list-in-box">
              <% @latest_items.each do |item| %>
                  <li class="item">

                    <div class="product-img">
                      <%= image_tag item.image.url(:thumb) %>
                    </div>

                    <div class="product-info" style="padding-top:15px;">
                      <a href="<%= item_path(item) %>" class="product-title">
                        <%= truncate item.name %>
                        <span class="label bg-aqua pull-right">$1800</span>
                      </a>
                      <!-- <span class="product-description">
                          Samsung 32" 1080p 60Hz LED Smart HDTV.
                        </span> -->
                    </div>

                  </li><!-- /.item -->
              <% end %>
            </ul>
            </div><!-- /.box-body -->
          <div class="box-footer text-center">
            <%= link_to 'View All Items', items_url, class: 'uppercase' %>
          </div><!-- /.box-footer -->

        <% else %>
          <div class="col-md-12 text-center" style="padding-top:30px;">
            <p class="lead">
              No items added
            </p>
          </div>
          <div class="box-footer text-center">
            &nbsp;
          </div><!-- /.box-footer -->
        <% end %>

    </div><!-- /.box -->
  </div><!-- /.col -->
</div>

<%#= render partial: 'client/items/form_modal',
           locals: { item: current_account.items.build, title: "Create item..." } %>